config/routes.rb
RunningSite::Application.routes.draw do
  resources :team_goals

  resources :day_items
  resources :exercises,               only: [:create, :destroy, :get_user_exercises] 
  resources :exercise_comments
  
  resources :notifications,           only: [:create, :destroy]
  resources :sessions,                only: [:new, :create, :destroy]
  resources :teams do
    member do
      get :list_team_member_data
      get :get_team_data_in_week
    end
  end
  resources :blog_posts
  resources :team_user_relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :teams
      get :list_exercises
      get :summary_of_exercises
      get :get_day_items
    end
  end

  root :to => 'static_pages#home'
  match '/get_user_data',          to: 'application#get_user_data', via: 'get'
  match '/get_team_data',          to: 'application#get_team_data', via: 'get'
  match '/get_users_teams',        to: 'application#get_users_teams', via: 'get'
  match '/get_all_teams',          to: 'application#get_all_teams', via: 'get'
  match '/get_user_data_for_month',to: 'application#get_user_data_for_month', via: 'get'
  match '/get_user_data_for_day',  to: 'application#get_user_data_for_day', via: 'get'
  match '/post_user_activity',     to: 'application#post_user_activity', via: 'post'
  match '/post_activity_comment',  to: 'application#post_activity_comment', via: 'post'
  match '/join_team',              to: 'application#join_team',via: 'post'
  match '/signin',                 to: 'sessions#new',         via: 'get'
  match '/signout',                to: 'sessions#destroy',     via: [:get, :post, :delete]
  match '/signup',                 to: 'users#new',            via: 'get'
  match '/help',                   to: 'static_pages#help',    via: 'get'
  match '/about',                  to: 'static_pages#about',   via: 'get'
  match '/contact',                to: 'static_pages#contact', via: 'get'
  match '/teams/new',              to: 'teams#new',            via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',      via: [:get, :post]
  match 'auth/failure',            to: redirect('/'),          via: [:get, :post]

end

app/models/team_goal.rb
class TeamGoal < ActiveRecord::Base
  belongs_to :team
end

app/controllers/team_goals_controller.rb
class TeamGoalsController < ApplicationController
  before_action :set_team_goal, only: [:show, :edit, :update, :destroy]

  # GET /team_goals
  # GET /team_goals.json
  def index
    @team_goals = TeamGoal.all
  end

  # GET /team_goals/1
  # GET /team_goals/1.json
  def show
  end

  # GET /team_goals/new
  def new
    @team_goal = TeamGoal.new
  end

  # GET /team_goals/1/edit
  def edit
  end

  # POST /team_goals
  # POST /team_goals.json
  def create
    @team_goal = TeamGoal.new(team_goal_params)

    respond_to do |format|
      if @team_goal.save
        format.html { redirect_to @team_goal, notice: 'Team goal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team_goal }
      else
        format.html { render action: 'new' }
        format.json { render json: @team_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_goals/1
  # PATCH/PUT /team_goals/1.json
  def update
    respond_to do |format|
      if @team_goal.update(team_goal_params)
        format.html { redirect_to @team_goal, notice: 'Team goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_goals/1
  # DELETE /team_goals/1.json
  def destroy
    @team_goal.destroy
    respond_to do |format|
      format.html { redirect_to team_goals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_goal
      @team_goal = TeamGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_goal_params
      params.require(:team_goal).permit(:team_id, :start_date, :end_date, :distance, :duration, :activity, :title)
    end
end

app/helpers/team_goals_helper.rb
module TeamGoalsHelper
end

app/views/team_goals/_form.html.erb
<%= simple_form_for(@team_goal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :team %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :distance %>
    <%= f.input :duration %>
    <%= f.input :activity %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/team_goals/edit.html.erb
<h1>Editing team_goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_goal %> |
<%= link_to 'Back', team_goals_path %>

app/views/team_goals/index.html.erb
<h1>Listing team_goals</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Distance</th>
      <th>Duration</th>
      <th>Activity</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @team_goals.each do |team_goal| %>
      <tr>
        <td><%= team_goal.team %></td>
        <td><%= team_goal.start_date %></td>
        <td><%= team_goal.end_date %></td>
        <td><%= team_goal.distance %></td>
        <td><%= team_goal.duration %></td>
        <td><%= team_goal.activity %></td>
        <td><%= team_goal.title %></td>
        <td><%= link_to 'Show', team_goal %></td>
        <td><%= link_to 'Edit', edit_team_goal_path(team_goal) %></td>
        <td><%= link_to 'Destroy', team_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team goal', new_team_goal_path %>

app/views/team_goals/new.html.erb
<h1>New team_goal</h1>

<%= render 'form' %>

<%= link_to 'Back', team_goals_path %>

app/views/team_goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_goal.team %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @team_goal.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @team_goal.end_date %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @team_goal.distance %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @team_goal.duration %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @team_goal.activity %>
</p>

<p>
  <strong>Title:</strong>
  <%= @team_goal.title %>
</p>

<%= link_to 'Edit', edit_team_goal_path(@team_goal) %> |
<%= link_to 'Back', team_goals_path %>