config/routes.rb
RunningSite::Application.routes.draw do
  resources :team_goals

  resources :day_items
  resources :exercises,               only: [:create, :destroy, :get_user_exercises] 
  resources :exercise_comments
  
  resources :notifications,           only: [:create, :destroy]
  resources :sessions,                only: [:new, :create, :destroy]
  resources :teams do
    member do
      get :list_team_member_data
      get :get_team_data_in_week
    end
  end
  resources :blog_posts
  resources :team_user_relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :teams
      get :list_exercises
      get :summary_of_exercises
      get :get_day_items
    end
  end

  root :to => 'static_pages#home'
  match '/get_user_data',          to: 'application#get_user_data', via: 'get'
  match '/get_team_data',          to: 'application#get_team_data', via: 'get'
  match '/get_users_teams',        to: 'application#get_users_teams', via: 'get'
  match '/get_all_teams',          to: 'application#get_all_teams', via: 'get'
  match '/get_user_data_for_month',to: 'application#get_user_data_for_month', via: 'get'
  match '/get_user_data_for_day',  to: 'application#get_user_data_for_day', via: 'get'
  match '/post_user_activity',     to: 'application#post_user_activity', via: 'post'
  match '/post_activity_comment',  to: 'application#post_activity_comment', via: 'post'
  match '/join_team',              to: 'application#join_team',via: 'post'
  match '/signin',                 to: 'sessions#new',         via: 'get'
  match '/signout',                to: 'sessions#destroy',     via: [:get, :post, :delete]
  match '/signup',                 to: 'users#new',            via: 'get'
  match '/help',                   to: 'static_pages#help',    via: 'get'
  match '/about',                  to: 'static_pages#about',   via: 'get'
  match '/contact',                to: 'static_pages#contact', via: 'get'
  match '/teams/new',              to: 'teams#new',            via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create',      via: [:get, :post]
  match 'auth/failure',            to: redirect('/'),          via: [:get, :post]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Designed by Brock Allen</small>
  <nav>
  	<ul>
  		<li><%= link_to "About", about_path %></li>
  		<li><%= link_to "Contact", contact_path %></li>
  		<li><%= link_to "Help", help_path %></li>
  	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "LogAJog", root_path, id:"logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Home", root_url, :class => "header-bar-title" %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle header-bar-title" data-toggle="dropdown">
                Teams <b class="caret white-caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% unless current_user.teams.nil? %>
                  <% current_user.teams.each do |team| %>
                    <% unless team.nil? %>
                      <li><%= link_to team.name, team %></li>
                    <% end %>
                  <% end %>
                  <li class="divider"></li>
                <% end %> 
                <li><%= link_to "Find Team", teams_path %></li>
                <li><%= link_to "Create Team", '/teams/new' %></li>
                <li class="divider"></li>
              </ul>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle header-bar-title" data-toggle="dropdown">
                Account <b class="caret white-caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=fullTitle(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "main" %>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:controller] %>">
  <div id="fb-root"></div>
    <script>
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=461347917304117";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
  <%= render 'layouts/header' %>
  <div class="containerWrapper">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>